In [ ]:
# https://projecteuler.net/problem=5

# 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

# What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [2]:
import numpy as np

In [18]:
from math import sqrt, gcd
from itertools import count, islice

In [10]:
def is_prime(n):
    return n > 1 and all(n % i for i in islice(count(2), int(sqrt(n)-1)))
n = 10
ns = np.arange(2,n+1, dtype=int)
primes = ns[np.vectorize(is_prime)(ns)]


In [11]:
primes

array([2, 3, 5, 7])

In [19]:
np.product(np.arange(2,n+1))//gcd(np.arange(2,n+1))

TypeError: gcd expected 2 arguments, got 1

In [14]:
2520//ns

array([1260,  840,  630,  504,  420,  360,  315,  280,  252], dtype=int32)

In [15]:
210//ns

array([105,  70,  52,  42,  35,  30,  26,  23,  21], dtype=int32)

In [17]:
2520/210

12.0

In [20]:
np.lcm(ns)

ValueError: invalid number of arguments